### ISSUE TITLE
debian stretch uninitialized constant Acme

### ISSUE THREAD

**Issue by lieblinger** [schubergphilis/chef-acme#100]
Hi,

on debian stretch I'm getting the following error when using the acme_certificate resource:

`

    NameError
    ---------
    uninitialized constant Acme
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/acme/libraries/acme.rb:36:in `acme_client'
    /var/chef/cache/cookbooks/acme/libraries/acme.rb:48:in `acme_authz_for'
    /var/chef/cache/cookbooks/acme/resources/certificate.rb:88:in `block (2 levels) in class_from_file'
    /var/chef/cache/cookbooks/acme/resources/certificate.rb:87:in `map'
    /var/chef/cache/cookbooks/acme/resources/certificate.rb:87:in `block in class_from_file'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/app-certificates/recipes/server.rb
    
     52:   acme_certificate "#{host}.#{node['app-certificates']['domain_name']}" do
     53:     key "#{node['app-certificates']['local_path']}#{host}.key"
     54:     fullchain "#{node['app-certificates']['local_path']}#{host}.crt"
     55:     chain "#{node['app-certificates']['local_path']}#{host}.pem"
     56:     wwwroot node['app-certificates']['wwwroot']
     57:   end
     58: end
`

Do you have any ideas to resolve this?

Regards Yannik

**Comment by hmacias** [comment]
In case somebody comes across this problem. I solved this by including acme recipe on top of my recipe like so in order to install **acme_client** gem:

`include_recipe 'acme'`
