### ISSUE TITLE
current master is failing (kitchen)

### ISSUE THREAD

**Issue by bottkv488** [schubergphilis/chef-acme#108]
Hi,
currently all kitchen runs are failing throwing a 

```shell
* acme_certificate[test.example.com] action create
    * file[test.example.com SSL key] action create_if_missing (up to date)

    ================================================================================
    Error executing action `create` on resource 'acme_certificate[test.example.com]'
    ================================================================================

    Acme::Client::Error::Malformed
    ------------------------------
    Method not allowed

    Cookbook Trace:
    ---------------
    /opt/kitchen/cache/cookbooks/acme/resources/certificate.rb:77:in `block in class_from_file'

```

Unlike https://travis-ci.org/schubergphilis/chef-acme/jobs/504736086 I see it failing on all platforms.

It appeared to me as some kind of regression due to pebble updates?
I'm quite sure that it used to work a couple of weeks ago.

I had to give up as I wasn't able to get useful debugging info either from pebble or from the acme-client gem when trying to reproduce the error and fired up boulder.

The resource `acme_certificate` works as expected when running against boulder.

I would be willing to help, but I got stuck here.

Regards, Bernhard

**Comment by thoutenbos** [comment]
Hi Bernhard,

Actually I got to the same point a few days ago when preparing a new release, so I can confirm I have the same issue in the kitchen. We'll need to investigate it a bit more to see what is happening. Haven't gotten around to that yet either.

Regards,
Thijs

**Comment by thoutenbos** [comment]
Build fixed
