### ISSUE TITLE
ACME server endpoint

### ISSUE THREAD

**Issue by Dragsbaek** [schubergphilis/chef-acme#110]
There seems to be inconsistencies between readme in Chef supermarket and Github. 

On supermarket, the attribute for setting endpoint is called "endpoint", and its using V1.

On github its called "dir", and using V2.

Which is correct?

**Comment by thoutenbos** [comment]
Version in supermarket is older than current master, so it was changed since the last release to the supermarket

Endpoint is correct for the version in the supermarked and dir is correct for current master in github
