### ISSUE TITLE
acme cookbook v4.0.0 (current in Supermarket) ACMEv1 only

### ISSUE THREAD

**Issue by SeanSith** [schubergphilis/chef-acme#112]
I am currently receiving the following error in my test environment:
```
Acme::Client::Error::Unauthorized
---------------------------------
Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a 
version that supports ACMEv2 / RFC 8555. See 
https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 
for details.
```
I have the following attributes set:
```
default['acme']['dir'] = 'https://acme-staging-v02.api.letsencrypt.org/directory/'
```

It seems that the issue lies in the fact that a new version of the cookbook has not been released to the Chef Supermarket and the current version lacks ACMEv2 support:
- The acme-client version in Supermarket cookbook (v4.0.0) is 0.6.2, ACMEv2 support is in acme-client 2.x.
- ACMEv1 support is [officially EoL from Let's Encrypt](https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430) in November 2019 for all new registrations, and all traffic in June 2020.

I have tested `5bd8e5c` with the above attribute and was able to get back a satisfactory response from the staging API endpoint.

I request that the maintainer release `master`, possibly with #111 merged (not personally tested, sorry). Thanks!

**Comment by SeanSith** [comment]
Please also consider #113 to avoid an unnecessary breaking change.

**Comment by thoutenbos** [comment]
New version released!
