### ISSUE TITLE
acme cookbook requesting for a certificate when a valid one already exists

### ISSUE THREAD

**Issue by jimmymbiyu** [schubergphilis/chef-acme#119]
Relevant software and versions

- chef-client: 15.1.36

- acme cookbook: ~> 4.1.1

When I ran my cookbooks the first time a few weeks ago, a new certificate was issued which is what I expected as the existing one was about to expire. 

Yesterday, I ran the cookbooks and noted the following:

- With the certificate being valid for another 64 days, the recipe attempted to request for another certificate. I did not specify a value for the renew attribute so the default value of 30 days should apply.

- The request failed with the following error.
```
* ruby_block[create certificate for <domain>] action run
================================================================================
Error executing action `run` on resource 'ruby_block[create certificate for <domain>]'
================================================================================

RuntimeError
------------
[<domain>] Validation failed, unable to request certificate

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/acme/resources/certificate.rb:111:in `block (3 levels) in class_from_file'

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/acme/resources/certificate.rb

108:     ruby_block "create certificate for #{new_resource.cn}" do # ~FC014
109:       block do
110:         unless (all_validations.map { |authz| authz.status == 'valid' }).all?
111:           fail "[#{new_resource.cn}] Validation failed, unable to request certificate"
112:         end
```

**Comment by ljapena** [comment]
@jimmymbiyu did you solve this issue ?? I'm having the same problem

**Comment by thoutenbos** [comment]
Validation failed means that the Let's Encrypt service was unable to request the validation file for your domain name. It is not a cookbook problem but a configuration problem on your end.

**Comment by ljapena** [comment]
Thanks @thoutenbos ! I'll check the domain.

**Comment by jimmymbiyu** [comment]
The acme cookbook no longer requests a new certificate when the days to certificate expiry are greater than `node['acme']['renew']`. @ljapena feel free to re-open the issue if the issue was not resolved for you.
