### ISSUE TITLE
new release 4.1.3 ?

### ISSUE THREAD

**Issue by ncoquelet** [schubergphilis/chef-acme#126]
Hi,

I have an error during the certificate validation, resources/certificate.rb line 108 and the recent update of PR #124 can help me to understand the problem.
How can I use the last master code on my environment ?

Thanks

**Comment by rwunderer** [comment]
+1 It would also be nice to upgrade `acme-client` gem to 2.0.8 for Chef 17 / Ruby 3.0 compatibility, avoiding this error:

 ```
 ArgumentError: wrong number of arguments (given 1, expected 0; required keywords: url, term_of_service, status, contact)
```

The currently used 2.0.6 version of this gem is not compatible with Ruby 3.0 as it doesn't yet include this PR: https://github.com/unixcharles/acme-client/pull/183

**Comment by nicutor** [comment]
+1
