### ISSUE TITLE
Also add "processing" as an authz.status

### ISSUE THREAD

**Issue by bugoff** [schubergphilis/chef-acme#133]
I use this cookbook and i use the tests in this cookbook to check if everything is working.

I noticed that the cookbook was still working in production, but not on my test environments, and everything points to pebble.

The error is:

           acme_certificate[le-ssl.defaultacc1.example.com] (xplose-nginx::proxy line 38) had an error: RuntimeError: ruby_block[create certificate for le-ssl.defaultacc1.example.com] (xplose-nginx::proxy line 110) had an error: RuntimeError: [le-ssl.defaultacc1.example.com] Validation failed, unable to request certificate, Errors: [{url: https://127.0.0.1:14000/chalZ/wLdHSb7os93pSoqao6Iosof_xvjSbkPz1xgCz3x7kHQ, status: processing, error: } ]

It looks like the chef-acme cookbook doesn't support the processing status. Not sure if there are other extra changes needed, but i could fix my local development by just adding the processing status to the validation check.
 
Pebble introduced "processing" as a new response:  https://github.com/letsencrypt/pebble/pull/382

**Comment by thoutenbos** [comment]
Thanks for the changes!
Will run the tests and release an update in the next few days
