### ISSUE TITLE
Certificate is not updated when common name / alternate names changed

### ISSUE THREAD

**Issue by acoulton** [schubergphilis/chef-acme#35]
The letsencrypt provider only creates a new certificate if the certificate file does not exist or if the certificate is approaching expiry. If there is a valid non-expired certificate on disk at the specified path then the provider does nothing.

I think it should also check that the common name and alternate names on the existing certificate match those declared on the resource, and provision a new certificate if any of those have changed?

**Comment by jldugger** [comment]
Ah, that explains why I had to remove the old cert before my altname setting took effect.
