### ISSUE TITLE
Deprecated features used - nil is an invalid value for path of resource file.

### ISSUE THREAD

**Issue by zeknox** [schubergphilis/chef-acme#47]
I'm creating a self signed certificate using the Letsencrypt cookbook.  The Certificates are generating perfectly fine but I'm getting a warning that I have set the Property path as nil.  Could someone provide any insight on what needs to be tweaked to eliminate the warning?

<pre>
$ chef -v
Chef Development Kit Version: 0.11.2
chef-client version: 12.9.41
berks version: 4.2.0
kitchen version: 1.5.0
</pre>

<pre>
include_recipe 'letsencrypt'

letsencrypt_selfsigned node['apache']['fqdn'] do
  crt     "/etc/ssl/#{node['apache']['fqdn']}.crt" 
  key     "/etc/ssl/#{node['apache']['fqdn']}.key"
end
</pre>

When converging, I'm getting the following Warnings that are shown below in the console and logs.

Deprecated features used!

<pre>
         nil is an invalid value for path of resource file. In Chef 13, this warning will change to an error. Error: Property path must be one of: String!  You passed nil. at 1 location:
           - /tmp/kitchen/cache/cookbooks/letsencrypt/providers/selfsigned.rb:44:in `block (2 levels) in class_from_file'
</pre>

**Comment by thoutenbos** [comment]
Hmm seems to be due to the way the `not_if` is evaluated in the chain file. You could work around the warning by providing the `chain` attribute to the provider.

Full Chef 13 compatibility for this cookbook still needs to be tested.

**Comment by thoutenbos** [comment]
Should be fixed now in master
