### ISSUE TITLE
New certificate request at each update ?

### ISSUE THREAD

**Issue by istopopoki** [schubergphilis/chef-acme#50]
Hello,
Is the cookbook requesting a new certificate every time I run chef-client on my server ?
If yes, is it a problem ?
If no, how do you renew existing certificates using this cookbook ?
Thanks

**Comment by thoutenbos** [comment]
It should request a certificate initially, and then renew it when the certificate has 30 days of validity left.

**Comment by istopopoki** [comment]
thanks
