### ISSUE TITLE
self-signed certs should probably have CA:TRUE constraint

### ISSUE THREAD

**Issue by timothy-spencer** [schubergphilis/chef-acme#55]
Otherwise code that checks for this (cough)go(cough) will bomb out.  Maybe there's a better way to do this, but I can't get self-signed certs to work with things like filebeat without this being set.

**Comment by timothy-spencer** [comment]
Maybe "should" is too strong.  Maybe it would be better to just let us optionally turn it on in the resource.

**Comment by thoutenbos** [comment]
Makes sense I guess, would accept a pull-request for it. Making it optional might be a bit overkill so adding this to all self-signed (temp) certs should be fine.

**Comment by thoutenbos** [comment]
Should be fixed in https://github.com/golang/go/commit/8ad70a549364c216c386afcead4dccfdcd39748b
