### ISSUE TITLE
Chef 11 

### ISSUE THREAD

**Issue by zeroedin** [schubergphilis/chef-acme#56]
Curious if this cookbook is compatible with Chef 11?  After digging it looks like the 1.0 releases were but they are not available on chef supermarket, any reason for that?

**Comment by thoutenbos** [comment]
The cookbook was named `letsencrypt` at that time, but was renamed to comply with the trademark policy.

https://supermarket.chef.io/cookbooks/letsencrypt

**Comment by zeroedin** [comment]
Gotcha, thanks!
