### ISSUE TITLE
chef13 deprecation warning

### ISSUE THREAD

**Issue by rmoriz** [schubergphilis/chef-acme#62]
> - property `method` of resource `acme_certificate` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. at 1 location:
> - /var/chef/cache/cookbooks/acme/resources/certificate.rb:36:in `class_from_file'

This is intentionally caused by a check in https://github.com/chef/chef/blob/master/lib/chef/property.rb#L610
and tracks probably down to https://ruby-doc.org/core-2.4.1/Object.html#method-i-method

I suggest we change this property (attribute) into something like `verification_method`?

**Comment by hudashot** [comment]
Any chance you could publish an updated version with this fix to the [Chef Supermarket](https://supermarket.chef.io/cookbooks/acme)?

**Comment by thoutenbos** [comment]
A new release is imminent when the last Chef 13 changes are in.

**Comment by rmoriz** [comment]
Afaik all changes are in. The only issue to track is the rabbitmq cookbook used in tests?

**Comment by thoutenbos** [comment]
Version 3.0.0 released in supermarket!
