### ISSUE TITLE
chef13 compat

### ISSUE THREAD

**Issue by dayne** [schubergphilis/chef-acme#74]
Looks like `chef-acme` needs a few chef13 compatibility updates.  

> [2017-04-26T18:16:45-08:00] WARN: Acme library dependency 'acme-client' not loaded: cannot load such file -- acme-client
> [2017-04-26T18:16:45-08:00] WARN: Property `method` of resource `acme_certificate` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. (CHEF-11)/tmp/chefspec20170426-3728-xy9n5rfile_cache_path/cookbooks/acme/resources/certificate.rb:36:in `class_from_file'.
> Please see https://docs.chef.io/deprecations_property_name_collision.html for further details and information on how to correct this problem. at /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/event_dispatch/dispatcher.rb:43:in `call'

**Comment by thoutenbos** [comment]
Try using the latest version ;)

**Comment by dayne** [comment]
Thanks.  Apparently updated that in a different cookbook and not the environment I was going gonzo to get all tests clean.

`berks update acme` brought in a happy and chef13 warning free solution.

Thanks!
