### ISSUE TITLE
authz.send returns nil

### ISSUE THREAD

**Issue by lonniev** [schubergphilis/chef-acme#87]
https://github.com/schubergphilis/chef-acme/blob/b49c28d8eeb2de4f05da3776458ad562a488aa7c/libraries/ssl_certificate.rb#L101

This call is returning nil rather than a legitimate validation instance. The object and the parameters look ok and the code did run in the past several months ago.

Did the acme-client gem change such that the send method is no longer working?

**Comment by infertux** [comment]
Same problem here. It used to work a few months ago.

I see it's using a fairly old version of the `acme-client` Gem: https://github.com/schubergphilis/chef-acme/blob/master/recipes/default.rb#L23

Perhaps upgrading to the latest [v0.6.2](https://rubygems.org/gems/acme-client/versions) would help @schubergphilis?

**Comment by thoutenbos** [comment]
I believe you are using the TLS-SNI-01 validation method (which is the acme_ssl_certificate provider in this cookbook), unfortunately this validation method has been disabled by Let's Encrypt:

https://community.letsencrypt.org/t/2018-01-11-update-regarding-acme-tls-sni-and-shared-hosting-infrastructure/50188

The new version of this cookbook will also remove this provider as it can no longer work now that this method is disabled at the CA. Please switch to the HTTP validation method.
