### ISSUE TITLE
Ubuntu 14.04 support

### ISSUE THREAD

**Issue by hrak** [schubergphilis/chef-acme#95]
Is there any reason why v4.0.0 only support Ubuntu 16.04? So far the cookbook has worked fine on 14.04 as well.

**Comment by thoutenbos** [comment]
No specific reason, it's just that testing is done on 16.04 but no reason why it wouldn't work on other versions.

**Comment by hrak** [comment]
@thoutenbos ok, but can you change the pin in metadata.rb to `supports 'ubuntu', '>= 14.04'` then? Because now its rather broken.
