### ISSUE TITLE
Invalid version constraint on metadata.platforms

### ISSUE THREAD

**Issue by hrak** [schubergphilis/chef-acme#96]
Using v4.0.0, when trying to upload the cookbook, the following error is thrown:

```
Response: Invalid value '~> 7' for metadata.platforms
```

Which is related to the centos platform pin in metadata.rb

**Comment by hrak** [comment]
or, in light of #95 use something more generic like

```
%w(ubuntu debian redhat centos fedora).each do |os|
  supports os
end
```

**Comment by thoutenbos** [comment]
Sounds good! Are you willing to make a PR for it?

**Comment by hrak** [comment]
Sure, here you go!

**Comment by thoutenbos** [comment]
Thank you!
