### ISSUE TITLE
Wildcard certificates support

### ISSUE THREAD

**Issue by gionn** [schubergphilis/chef-acme#98]
It would be nice to update to acme-client v2 in order to support wildcard certificates

**Comment by thoutenbos** [comment]
> Under Let’s Encrypt’s policy, wildcard identifiers must be validated by a DNS-01 challenge, so order authorizations corresponding to wildcard identifiers will only offer a DNS-01 challenge.

Currently the DNS-01 challenge is not supported by this cookbook. Adding it would involve adding support for interacting with the authoritative DNS configuration for a domain, which is very situation specific. Until DNS-01 challenges are supported it will not be possible to request wildcard certificates.
